# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'student_grade_calc_gui_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import control


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(926, 683)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(300, 10, 141, 41))
        self.title.setObjectName("title")
        self.StudentDataLabel = QtWidgets.QLabel(self.centralwidget)
        self.StudentDataLabel.setGeometry(QtCore.QRect(60, 70, 191, 16))
        self.StudentDataLabel.setObjectName("StudentDataLabel")
        self.StudentData = QtWidgets.QTextEdit(self.centralwidget)
        self.StudentData.setGeometry(QtCore.QRect(270, 70, 311, 91))
        self.StudentData.setObjectName("StudentData")
        self.calculateButton = QtWidgets.QPushButton(self.centralwidget)
        self.calculateButton.setGeometry(QtCore.QRect(520, 180, 161, 31))
        self.calculateButton.setObjectName("calculateButton")
        self.calculateButton.clicked.connect(lambda:control.calculate_grades(self))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 926, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Student Grade Calculator"))
        self.title.setText(_translate("MainWindow", "Student Grade Calculator"))
        self.StudentDataLabel.setText(_translate("MainWindow", "Enter student names and scores:"))
        self.StudentData.setPlaceholderText(_translate("MainWindow", "Enter student names and scores: (separate names and scores by commas, and put one student on each line)"))
        self.calculateButton.setText(_translate("MainWindow", "Calculate Grade Report"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
