# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'student_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import control


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 500)
        MainWindow.setMinimumSize(QtCore.QSize(900, 500))
        MainWindow.setMaximumSize(QtCore.QSize(900, 500))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.TitleLabel = QtWidgets.QLabel(self.centralwidget)
        self.TitleLabel.setGeometry(QtCore.QRect(380, 20, 121, 16))
        self.TitleLabel.setObjectName("TitleLabel")
        self.AddStudentButton = QtWidgets.QPushButton(self.centralwidget)
        self.AddStudentButton.setGeometry(QtCore.QRect(530, 290, 141, 28))
        self.AddStudentButton.setObjectName("AddStudentButton")
        self.DeleteStudentButton = QtWidgets.QPushButton(self.centralwidget)
        self.DeleteStudentButton.setGeometry(QtCore.QRect(690, 290, 141, 28))
        self.DeleteStudentButton.setObjectName("DeleteStudentButton")
        self.AddDeleteLabel = QtWidgets.QLabel(self.centralwidget)
        self.AddDeleteLabel.setGeometry(QtCore.QRect(640, 130, 111, 16))
        self.AddDeleteLabel.setObjectName("AddDeleteLabel")
        self.NameLabel = QtWidgets.QLabel(self.centralwidget)
        self.NameLabel.setGeometry(QtCore.QRect(570, 200, 55, 16))
        self.NameLabel.setObjectName("NameLabel")
        self.nameInput = QtWidgets.QLineEdit(self.centralwidget)
        self.nameInput.setGeometry(QtCore.QRect(610, 200, 221, 22))
        self.nameInput.setObjectName("nameInput")
        self.ScoreLabel = QtWidgets.QLabel(self.centralwidget)
        self.ScoreLabel.setGeometry(QtCore.QRect(570, 240, 55, 16))
        self.ScoreLabel.setObjectName("ScoreLabel")
        self.scoreInput = QtWidgets.QLineEdit(self.centralwidget)
        self.scoreInput.setGeometry(QtCore.QRect(610, 240, 221, 22))
        self.scoreInput.setObjectName("scoreInput")
        self.errorLabel = QtWidgets.QLabel(self.centralwidget)
        self.errorLabel.setGeometry(QtCore.QRect(440, 370, 401, 21))
        self.errorLabel.setText("")
        self.errorLabel.setObjectName("errorLabel")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 60, 81, 16))
        self.label.setObjectName("label")
        self.studentNamesLabel = QtWidgets.QLabel(self.centralwidget)
        self.studentNamesLabel.setGeometry(QtCore.QRect(30, 100, 91, 16))
        self.studentNamesLabel.setObjectName("studentNamesLabel")
        self.studentScoresLabel = QtWidgets.QLabel(self.centralwidget)
        self.studentScoresLabel.setGeometry(QtCore.QRect(150, 100, 91, 16))
        self.studentScoresLabel.setObjectName("studentScoresLabel")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(270, 100, 91, 16))
        self.label_2.setObjectName("label_2")
        self.studentNamesList = QtWidgets.QTextBrowser(self.centralwidget)
        self.studentNamesList.setGeometry(QtCore.QRect(30, 130, 121, 271))
        self.studentNamesList.setObjectName("studentNamesList")
        self.studentScoresList = QtWidgets.QTextBrowser(self.centralwidget)
        self.studentScoresList.setGeometry(QtCore.QRect(150, 130, 121, 271))
        self.studentScoresList.setObjectName("studentScoresList")
        self.studentGradesList = QtWidgets.QTextBrowser(self.centralwidget)
        self.studentGradesList.setGeometry(QtCore.QRect(270, 130, 111, 271))
        self.studentGradesList.setObjectName("studentGradesList")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.AddStudentButton.clicked.connect(lambda:control.add_student(self))
        self.DeleteStudentButton.clicked.connect(lambda:control.delete_student(self))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Student Grade Scaler"))
        self.TitleLabel.setText(_translate("MainWindow", "Student Grade Scaler"))
        self.AddStudentButton.setText(_translate("MainWindow", "Add/Change Student"))
        self.DeleteStudentButton.setText(_translate("MainWindow", "Delete Student"))
        self.AddDeleteLabel.setText(_translate("MainWindow", "Add/Delete Student"))
        self.NameLabel.setText(_translate("MainWindow", "Name:"))
        self.ScoreLabel.setText(_translate("MainWindow", "Score:"))
        self.label.setText(_translate("MainWindow", "Grade Report"))
        self.studentNamesLabel.setText(_translate("MainWindow", "Student Names"))
        self.studentScoresLabel.setText(_translate("MainWindow", "Student Scores"))
        self.label_2.setText(_translate("MainWindow", "Student Grades"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
