# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'student_grade_calc_gui_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(757, 218)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(300, 10, 141, 41))
        self.title.setObjectName("title")
        self.label_num_students = QtWidgets.QLabel(self.centralwidget)
        self.label_num_students.setGeometry(QtCore.QRect(110, 60, 151, 41))
        self.label_num_students.setObjectName("label_num_students")
        self.num_students = QtWidgets.QLineEdit(self.centralwidget)
        self.num_students.setGeometry(QtCore.QRect(270, 70, 113, 22))
        self.num_students.setObjectName("num_students")
        self.NextButton = QtWidgets.QPushButton(self.centralwidget)
        self.NextButton.setGeometry(QtCore.QRect(470, 130, 93, 28))
        self.NextButton.setObjectName("NextButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 757, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Student Grade Calculator"))
        self.title.setText(_translate("MainWindow", "Student Grade Calculator"))
        self.label_num_students.setText(_translate("MainWindow", "Enter number of students: "))
        self.NextButton.setText(_translate("MainWindow", "Next"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
